/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import ConectDB.*;
import GUI.*;
import ConectDB.ConnectionUtil;
import java.awt.Color;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author MSI
 */
public class giaovien extends javax.swing.JFrame {

    /**
     * Creates new form insertsv
     */
    public giaovien() throws SQLException, ClassNotFoundException {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
        txtmsgv.setBackground(new Color(0,0,0,0));
        txthoten.setBackground(new Color(0,0,0,0));
        txtlop.setBackground(new Color(0,0,0,0));
        txtsdt.setBackground(new Color(0,0,0,0));
        txtdiachi.setBackground(new Color(0,0,0,0));
        txtmsgvcu.setBackground(new Color(0,0,0,0));
        showGVcomboboxmshh(cbmshh);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtmsgvcu = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtdiachi = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txtsdt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        cbmshh = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        txtlop = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        txthoten = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        txtmsgv = new javax.swing.JTextField();
        labelmsgv = new javax.swing.JLabel();
        nhan2 = new javax.swing.JLabel();
        btnback = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nhan1 = new javax.swing.JLabel();
        btninsertgv = new javax.swing.JLabel();
        btneditgv = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        bg1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtmsgvcu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtmsgvcu.setForeground(new java.awt.Color(255, 255, 255));
        txtmsgvcu.setText("Enter MSGV cũ");
        txtmsgvcu.setBorder(null);
        txtmsgvcu.setCaretColor(new java.awt.Color(255, 255, 255));
        txtmsgvcu.setOpaque(false);
        txtmsgvcu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtmsgvcuFocusGained(evt);
            }
        });
        txtmsgvcu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtmsgvcuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtmsgvcuMouseExited(evt);
            }
        });
        txtmsgvcu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmsgvcuActionPerformed(evt);
            }
        });
        getContentPane().add(txtmsgvcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 320, 40));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator8.setToolTipText("");
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 10, 500));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 330, 20));

        jLabel8.setFont(new java.awt.Font("UTM Avo", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Địa chỉ:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 160, 40));

        txtdiachi.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtdiachi.setForeground(new java.awt.Color(255, 255, 255));
        txtdiachi.setText("Enter DIACHI_GV");
        txtdiachi.setBorder(null);
        txtdiachi.setCaretColor(new java.awt.Color(255, 255, 255));
        txtdiachi.setOpaque(false);
        txtdiachi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtdiachiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtdiachiMouseExited(evt);
            }
        });
        txtdiachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiachiActionPerformed(evt);
            }
        });
        getContentPane().add(txtdiachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 320, 40));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 610, 332, 10));

        txtsdt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtsdt.setForeground(new java.awt.Color(255, 255, 255));
        txtsdt.setText("Enter SODT_GV");
        txtsdt.setBorder(null);
        txtsdt.setCaretColor(new java.awt.Color(255, 255, 255));
        txtsdt.setOpaque(false);
        txtsdt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtsdtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtsdtMouseExited(evt);
            }
        });
        txtsdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsdtActionPerformed(evt);
            }
        });
        getContentPane().add(txtsdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 320, 40));

        jLabel7.setFont(new java.awt.Font("UTM Avo", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Số điện thoại:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 160, 40));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 332, 10));

        getContentPane().add(cbmshh, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 310, 30));

        jLabel6.setFont(new java.awt.Font("UTM Avo", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Năm học hàm và MSHH:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 270, 30));

        txtlop.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtlop.setForeground(new java.awt.Color(255, 255, 255));
        txtlop.setText("Enter NAMHH");
        txtlop.setBorder(null);
        txtlop.setCaretColor(new java.awt.Color(255, 255, 255));
        txtlop.setOpaque(false);
        txtlop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtlopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtlopMouseExited(evt);
            }
        });
        txtlop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlopActionPerformed(evt);
            }
        });
        getContentPane().add(txtlop, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 320, 30));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(0, 4));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 332, 10));

        jLabel5.setFont(new java.awt.Font("UTM Avo", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Họ và tên:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 160, 40));

        txthoten.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txthoten.setForeground(new java.awt.Color(255, 255, 255));
        txthoten.setText("Enter TENGV");
        txthoten.setBorder(null);
        txthoten.setCaretColor(new java.awt.Color(255, 255, 255));
        txthoten.setOpaque(false);
        txthoten.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txthotenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txthotenMouseExited(evt);
            }
        });
        getContentPane().add(txthoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 320, 40));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 332, 10));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 332, 10));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");
        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 10, 500));

        txtmsgv.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtmsgv.setForeground(new java.awt.Color(255, 255, 255));
        txtmsgv.setText("Enter MSGV");
        txtmsgv.setBorder(null);
        txtmsgv.setCaretColor(new java.awt.Color(255, 255, 255));
        txtmsgv.setOpaque(false);
        txtmsgv.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtmsgvFocusGained(evt);
            }
        });
        txtmsgv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtmsgvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtmsgvMouseExited(evt);
            }
        });
        getContentPane().add(txtmsgv, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 320, 40));

        labelmsgv.setFont(new java.awt.Font("UTM Avo", 1, 18)); // NOI18N
        labelmsgv.setForeground(new java.awt.Color(255, 255, 255));
        labelmsgv.setText("Mã số giáo viên: ");
        getContentPane().add(labelmsgv, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 320, 40));

        nhan2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nhan2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit_property_100px.png"))); // NOI18N
        nhan2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nhan2MouseClicked(evt);
            }
        });
        getContentPane().add(nhan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/undo_60px.png"))); // NOI18N
        btnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbackMouseClicked(evt);
            }
        });
        getContentPane().add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 640, -1, -1));

        jLabel2.setFont(new java.awt.Font("UTM Avo", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Thông tin giáo viên");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, 40));

        nhan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_row_100px.png"))); // NOI18N
        getContentPane().add(nhan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        btninsertgv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_60px.png"))); // NOI18N
        btninsertgv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btninsertgvMouseClicked(evt);
            }
        });
        getContentPane().add(btninsertgv, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 640, -1, -1));

        btneditgv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btneditgv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit_property_100px.png"))); // NOI18N
        btneditgv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneditgvMouseClicked(evt);
            }
        });
        getContentPane().add(btneditgv, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 640, -1, -1));

        bg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/insertsv.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 711));

        bg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/insertsv.png"))); // NOI18N
        getContentPane().add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 21, -1, 711));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnbackMouseClicked

    private void nhan2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhan2MouseClicked
        try {
            String mssv = txtmsgv.getText();
            String tensv = txthoten.getText();
            String lop = txtlop.getText();
            String sodt = txtsdt.getText();
            String diachi = txtdiachi.getText();
            Connection conn;
            conn = ConnectionUtil.getMyConnection();
            String sql = "{call insert_table_sinhvien(?,?,?,?,?,?)}";
            CallableStatement cstm = conn.prepareCall(sql);
            cstm.setString(1, mssv);
            cstm.setString(2, tensv);
            cstm.setString(3, lop);
            cstm.setString(4, sodt);
            cstm.setString(5, diachi);
            cstm.registerOutParameter(6, java.sql.Types.INTEGER);
            cstm.executeUpdate();
            int kq= cstm.getInt(6);//gọi kết quả trả về
            if(kq==1){
                JOptionPane.showMessageDialog(null,"Insert Complete!!!!");
            }else{
                JOptionPane.showMessageDialog(null,"Fail! Please check and insert againt!!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(giaovien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(giaovien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nhan2MouseClicked

    private void txtlopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlopActionPerformed

    private void txtsdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsdtActionPerformed

    private void txtdiachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiachiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiachiActionPerformed

    private void txtmsgvFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmsgvFocusGained
        
    }//GEN-LAST:event_txtmsgvFocusGained

    private void txthotenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txthotenMouseEntered
        
    }//GEN-LAST:event_txthotenMouseEntered

    private void txtlopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtlopMouseEntered
        
    }//GEN-LAST:event_txtlopMouseEntered

    private void txtsdtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsdtMouseEntered
        
    }//GEN-LAST:event_txtsdtMouseEntered

    private void txtdiachiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdiachiMouseExited
        
    }//GEN-LAST:event_txtdiachiMouseExited

    private void txtdiachiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdiachiMouseEntered
       
    }//GEN-LAST:event_txtdiachiMouseEntered

    private void txtmsgvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmsgvMouseExited
        
    }//GEN-LAST:event_txtmsgvMouseExited

    private void txthotenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txthotenMouseExited
        
    }//GEN-LAST:event_txthotenMouseExited

    private void txtlopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtlopMouseExited
        
    }//GEN-LAST:event_txtlopMouseExited

    private void txtsdtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsdtMouseExited
        
    }//GEN-LAST:event_txtsdtMouseExited

    private void txtmsgvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmsgvMouseEntered
        txtmsgv.setText("");
        txthoten.setText("");
        txtdiachi.setText("");
        txtsdt.setText("");
        txtlop.setText("");
    }//GEN-LAST:event_txtmsgvMouseEntered
    private void showGVcomboboxmshh(JComboBox tenbien) throws SQLException, ClassNotFoundException
    {
        tenbien.removeAllItems();
        Connection conn =  ConnectionUtil.getMyConnection();
        Statement st = conn.createStatement();
        String sqlcheck="select MSHH from HOCHAM";
        ResultSet rs=st.executeQuery(sqlcheck);
        while(rs.next()){
            cbmshh.addItem(rs.getString("MSHH"));
        } 
    }
    private void btninsertgvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btninsertgvMouseClicked
        try {
            String msgv = txtmsgv.getText();
            String tensv = txthoten.getText();
            String namhh = txtlop.getText();
            String sodt = txtsdt.getText();
            String diachi = txtdiachi.getText();
            String mshh = cbmshh.getSelectedItem().toString();
            Connection conn;
            conn = ConnectionUtil.getMyConnection();
            String sql = "{call insert_giaovien(?,?,?,?,?,?,?)}";
            CallableStatement cstm = conn.prepareCall(sql);
            cstm.setString(1, msgv);
            cstm.setString(2, mshh);
            cstm.setString(3, tensv);
            cstm.setString(4, diachi);
            cstm.setString(5, sodt);
            cstm.setString(6, namhh);
            cstm.registerOutParameter(7, java.sql.Types.INTEGER);
            cstm.executeUpdate();
            int kq= cstm.getInt(7);//gọi kết quả trả về
            if(kq==1){
                JOptionPane.showMessageDialog(null,"Insert Complete!!!!");
            }else{
                JOptionPane.showMessageDialog(null,"Fail! Please check and insert againt!!");
            }
        } catch (SQLException ex) {
        } catch (ClassNotFoundException ex) {
        }
    }//GEN-LAST:event_btninsertgvMouseClicked

    private void btneditgvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditgvMouseClicked
        try {
            String msgvcu = txtmsgvcu.getText();
            String mssvmoi = txtmsgv.getText();
            String namhh = txtlop.getText();
            String mshh = cbmshh.getSelectedItem().toString();
            String sodt = txtsdt.getText();
            Connection conn;
            conn = ConnectionUtil.getMyConnection();
            String sql = "{call capnhatgiaovien(?,?,?,?,?,?)}";
            CallableStatement cstm = conn.prepareCall(sql);
            cstm.setString(1, msgvcu);
            cstm.setString(2, mssvmoi);
            cstm.setString(3, mshh);
            cstm.setString(4, sodt);
            cstm.setString(5, namhh);
            cstm.registerOutParameter(6, java.sql.Types.INTEGER);
            cstm.executeUpdate();
            int kq= cstm.getInt(6);//gọi kết quả trả về
            if(kq==1){
                JOptionPane.showMessageDialog(null,"Update Complete!!!!");
            }else{
                JOptionPane.showMessageDialog(null,"Fail! Please check and update againt!!");
            }
        } catch (SQLException ex) {
        } catch (ClassNotFoundException ex) {
        }
    }//GEN-LAST:event_btneditgvMouseClicked

    private void txtmsgvcuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmsgvcuFocusGained
          txtmsgvcu.setText("");
    }//GEN-LAST:event_txtmsgvcuFocusGained

    private void txtmsgvcuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmsgvcuMouseEntered
      
    }//GEN-LAST:event_txtmsgvcuMouseEntered

    private void txtmsgvcuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmsgvcuMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmsgvcuMouseExited

    private void txtmsgvcuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmsgvcuActionPerformed
        
    }//GEN-LAST:event_txtmsgvcuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(giaovien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(giaovien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(giaovien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(giaovien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new giaovien().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(giaovien.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(giaovien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bg1;
    private javax.swing.JLabel btnback;
    public static javax.swing.JLabel btneditgv;
    public static javax.swing.JLabel btninsertgv;
    private javax.swing.JComboBox cbmshh;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    public static javax.swing.JLabel labelmsgv;
    public static javax.swing.JLabel nhan1;
    public static javax.swing.JLabel nhan2;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtlop;
    private javax.swing.JTextField txtmsgv;
    public static javax.swing.JTextField txtmsgvcu;
    private javax.swing.JTextField txtsdt;
    // End of variables declaration//GEN-END:variables
}
