/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.*;
import ConectDB.*;
import GUI.*;
import ConectDB.ConnectionUtil;
import ConectDB.ConnectionUtil;
import java.awt.Color;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author MSI
 */
public class GV_HV_CN_GUI extends javax.swing.JFrame {

    /**
     * Creates new form insertsv
     */
    public GV_HV_CN_GUI() throws SQLException, ClassNotFoundException {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
        txtmsgv.setBackground(new Color(0,0,0,0));
        txtcn.setBackground(new Color(0,0,0,0));
        txtnam.setBackground(new Color(0,0,0,0));
        txthocvi.setBackground(new Color(0,0,0,0));
        showGVcomboboxmshh(cbmshv);
        showGVcomboboxmscn(cbmscn);
        showGVcombobotxtmsgvcu(txtmsgvcu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator8 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txtmsgvcu = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cbmscn = new javax.swing.JComboBox();
        cbmshv = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        txthocvi = new javax.swing.JTextField();
        txtnam = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        txtcn = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        txtmsgv = new javax.swing.JTextField();
        labelmsgv = new javax.swing.JLabel();
        nhan2 = new javax.swing.JLabel();
        btnback = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nhan1 = new javax.swing.JLabel();
        btninsertgv = new javax.swing.JLabel();
        btneditgv = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        bg1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator8.setToolTipText("");
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 10, 500));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 330, 20));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 610, 332, 10));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 332, 10));

        txtmsgvcu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtmsgvcuItemStateChanged(evt);
            }
        });
        getContentPane().add(txtmsgvcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 310, 30));

        jLabel7.setFont(new java.awt.Font("UTM Avo", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Năm:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 270, 30));

        cbmscn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbmscnItemStateChanged(evt);
            }
        });
        getContentPane().add(cbmscn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 310, 30));

        cbmshv.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbmshvItemStateChanged(evt);
            }
        });
        getContentPane().add(cbmshv, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 310, 30));

        jLabel6.setFont(new java.awt.Font("UTM Avo", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mã số học vị:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 270, 30));

        txthocvi.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txthocvi.setForeground(new java.awt.Color(255, 255, 255));
        txthocvi.setText("Tên học vị:");
        txthocvi.setBorder(null);
        txthocvi.setCaretColor(new java.awt.Color(255, 255, 255));
        txthocvi.setOpaque(false);
        txthocvi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txthocviMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txthocviMouseExited(evt);
            }
        });
        getContentPane().add(txthocvi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 320, 40));

        txtnam.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtnam.setForeground(new java.awt.Color(255, 255, 255));
        txtnam.setText("Enter NAM");
        txtnam.setBorder(null);
        txtnam.setCaretColor(new java.awt.Color(255, 255, 255));
        txtnam.setOpaque(false);
        txtnam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtnamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtnamMouseExited(evt);
            }
        });
        txtnam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamActionPerformed(evt);
            }
        });
        getContentPane().add(txtnam, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 320, 40));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(0, 4));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 332, 10));

        jLabel5.setFont(new java.awt.Font("UTM Avo", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mã số chuyên ngành:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 320, 40));

        txtcn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtcn.setForeground(new java.awt.Color(255, 255, 255));
        txtcn.setText("Chuyên ngành");
        txtcn.setBorder(null);
        txtcn.setCaretColor(new java.awt.Color(255, 255, 255));
        txtcn.setOpaque(false);
        txtcn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtcnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtcnMouseExited(evt);
            }
        });
        getContentPane().add(txtcn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 320, 40));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 332, 10));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 332, 10));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");
        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 10, 500));

        txtmsgv.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtmsgv.setForeground(new java.awt.Color(255, 255, 255));
        txtmsgv.setText("Enter MSGV");
        txtmsgv.setBorder(null);
        txtmsgv.setCaretColor(new java.awt.Color(255, 255, 255));
        txtmsgv.setOpaque(false);
        txtmsgv.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtmsgvFocusGained(evt);
            }
        });
        txtmsgv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtmsgvMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtmsgvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtmsgvMouseExited(evt);
            }
        });
        getContentPane().add(txtmsgv, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 320, 40));

        labelmsgv.setFont(new java.awt.Font("UTM Avo", 1, 18)); // NOI18N
        labelmsgv.setForeground(new java.awt.Color(255, 255, 255));
        labelmsgv.setText("Mã số giáo viên: ");
        getContentPane().add(labelmsgv, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 320, 40));

        nhan2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nhan2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit_property_100px.png"))); // NOI18N
        nhan2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nhan2MouseClicked(evt);
            }
        });
        getContentPane().add(nhan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/undo_60px.png"))); // NOI18N
        btnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbackMouseClicked(evt);
            }
        });
        getContentPane().add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 640, -1, -1));

        jLabel2.setFont(new java.awt.Font("UTM Avo", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Thông tin chuyên môn");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, 40));

        nhan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_row_100px.png"))); // NOI18N
        getContentPane().add(nhan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        btninsertgv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_60px.png"))); // NOI18N
        btninsertgv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btninsertgvMouseClicked(evt);
            }
        });
        getContentPane().add(btninsertgv, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 630, -1, -1));

        btneditgv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btneditgv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit_property_100px.png"))); // NOI18N
        btneditgv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneditgvMouseClicked(evt);
            }
        });
        getContentPane().add(btneditgv, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 630, -1, -1));

        bg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/insertsv.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 711));

        bg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/insertsv.png"))); // NOI18N
        getContentPane().add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 21, -1, 711));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnbackMouseClicked

    private void nhan2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhan2MouseClicked
        try {
            String mssv = txtmsgv.getText();
            String tensv = txtcn.getText();
            String lop = txtnam.getText();
            
            Connection conn;
            conn = ConnectionUtil.getMyConnection();
            String sql = "{call insert_table_sinhvien(?,?,?,?,?,?)}";
            CallableStatement cstm = conn.prepareCall(sql);
            cstm.setString(1, mssv);
            cstm.setString(2, tensv);
            cstm.setString(3, lop);
            
            cstm.registerOutParameter(6, java.sql.Types.INTEGER);
            cstm.executeUpdate();
            int kq= cstm.getInt(6);//gọi kết quả trả về
            if(kq==1){
                JOptionPane.showMessageDialog(null,"Insert Complete!!!!");
            }else{
                JOptionPane.showMessageDialog(null,"Fail! Please check and insert againt!!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(GV_HV_CN_GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GV_HV_CN_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nhan2MouseClicked

    private void txtnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamActionPerformed

    private void txtmsgvFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmsgvFocusGained
        
    }//GEN-LAST:event_txtmsgvFocusGained

    private void txtcnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcnMouseEntered
        
    }//GEN-LAST:event_txtcnMouseEntered

    private void txtnamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnamMouseEntered
        
    }//GEN-LAST:event_txtnamMouseEntered

    private void txtmsgvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmsgvMouseExited
        
    }//GEN-LAST:event_txtmsgvMouseExited

    private void txtcnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcnMouseExited
        
    }//GEN-LAST:event_txtcnMouseExited

    private void txtnamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnamMouseExited
        
    }//GEN-LAST:event_txtnamMouseExited

    private void txtmsgvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmsgvMouseEntered
        txtmsgv.setText("");
        txtnam.setText("");
    }//GEN-LAST:event_txtmsgvMouseEntered
    private void showGVcomboboxmshh(JComboBox tenbien) throws SQLException, ClassNotFoundException
    {
        tenbien.removeAllItems();
        Connection conn =  ConnectionUtil.getMyConnection();
        Statement st = conn.createStatement();
        String sqlcheck="select MSHV from HOCVI";
        ResultSet rs=st.executeQuery(sqlcheck);
        while(rs.next()){
            cbmshv.addItem(rs.getString("MSHV"));
        } 
    }
    private void showGVcombobotxtmsgvcu(JComboBox tenbien) throws SQLException, ClassNotFoundException
    {
        tenbien.removeAllItems();
        Connection conn =  ConnectionUtil.getMyConnection();
        Statement st = conn.createStatement();
        String sqlcheck="select MSGV from GV_HV_CN";
        ResultSet rs=st.executeQuery(sqlcheck);
        while(rs.next()){
            txtmsgvcu.addItem(rs.getString("MSGV"));
        } 
    }
    private void showhocvi(JComboBox tenbien) throws SQLException, ClassNotFoundException
    {
        String mscn = tenbien.getSelectedItem().toString();
        Connection conn =  ConnectionUtil.getMyConnection();
        Statement st = conn.createStatement();
        String sqlcheck="select TENHV from HOCVI where MSHV = '"+mscn+"'";
        ResultSet rs=st.executeQuery(sqlcheck);
        while(rs.next()){
            String kq = (rs.getString("TENHV"));
            txthocvi.setText(kq);
        } 
    }
     private void showGVcomboboxmscn(JComboBox tenbien) throws SQLException, ClassNotFoundException
    {
        tenbien.removeAllItems();
        Connection conn =  ConnectionUtil.getMyConnection();
        Statement st = conn.createStatement();
        String sqlcheck="select MSCN from CHUYENNGANH";
        ResultSet rs=st.executeQuery(sqlcheck);
        while(rs.next()){
            cbmscn.addItem(rs.getString("MSCN"));
        } 
    }
    private void showchuyennganh(JComboBox tenbien) throws SQLException, ClassNotFoundException
    {
        String mscn = tenbien.getSelectedItem().toString();
        Connection conn =  ConnectionUtil.getMyConnection();
        Statement st = conn.createStatement();
        String sqlcheck="select TENCN from CHUYENNGANH where MSCN = '"+mscn+"'";
        ResultSet rs=st.executeQuery(sqlcheck);
        while(rs.next()){
            String kq = (rs.getString("TENCN"));
            txtcn.setText(kq);
        } 
    }
    private void btninsertgvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btninsertgvMouseClicked
        try {
            String msgv = txtmsgv.getText();
            String mscn = cbmscn.getSelectedItem().toString();
            String namhh = txtnam.getText();
            String mshv = cbmshv.getSelectedItem().toString();
            Connection conn;
            conn = ConnectionUtil.getMyConnection();
            String sql = "{call insert_gv_hv_cn(?,?,?,?,?)}";
            CallableStatement cstm = conn.prepareCall(sql);
            cstm.setString(1, msgv);
            cstm.setString(2, mscn);
            cstm.setString(3, mshv);
            cstm.setString(4, namhh);
            cstm.registerOutParameter(5, java.sql.Types.INTEGER);
            cstm.executeUpdate();
            int kq= cstm.getInt(5);//gọi kết quả trả về
            if(kq==1){
                JOptionPane.showMessageDialog(null,"Insert Complete!!!!");
            }else{
                JOptionPane.showMessageDialog(null,"Fail! Please check and insert againt!!");
            }
        } catch (SQLException | ClassNotFoundException ex) {
        }
    }//GEN-LAST:event_btninsertgvMouseClicked

    private void btneditgvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditgvMouseClicked
        try {
            String msgvcu = txtmsgvcu.getSelectedItem().toString();
            System.out.print(msgvcu);
            String namhh = txtnam.getText();
            String mshv = cbmshv.getSelectedItem().toString();
            Connection conn;
            conn = ConnectionUtil.getMyConnection();
            String sql = "{call capnhatgv_hv_cn(?,?,?,?)}";
            CallableStatement cstm = conn.prepareCall(sql);
            cstm.setString(1, msgvcu);
            cstm.setString(2, mshv);
            cstm.setString(3, namhh);
            cstm.registerOutParameter(4, java.sql.Types.INTEGER);
            cstm.executeUpdate();
            int kq= cstm.getInt(4);//gọi kết quả trả về
            if(kq==1){
                JOptionPane.showMessageDialog(null,"Update Complete!!!!");
            }else{
                JOptionPane.showMessageDialog(null,"Fail! Please check and update againt!!");
            }
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Fail! Please check and update againt!!");
        }
    }//GEN-LAST:event_btneditgvMouseClicked

    private void txthocviMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txthocviMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txthocviMouseEntered

    private void txthocviMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txthocviMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txthocviMouseExited

    private void txtmsgvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmsgvMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmsgvMouseClicked

    private void cbmscnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbmscnItemStateChanged
        try {
            showchuyennganh(cbmscn);
        } catch (SQLException ex) {
        } catch (ClassNotFoundException ex) {
        }
    }//GEN-LAST:event_cbmscnItemStateChanged

    private void cbmshvItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbmshvItemStateChanged
        try {
            showhocvi(cbmshv);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(GV_HV_CN_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbmshvItemStateChanged

    private void txtmsgvcuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtmsgvcuItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmsgvcuItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GV_HV_CN_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GV_HV_CN_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GV_HV_CN_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GV_HV_CN_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GV_HV_CN_GUI().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(GV_HV_CN_GUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(GV_HV_CN_GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bg1;
    private javax.swing.JLabel btnback;
    public static javax.swing.JLabel btneditgv;
    public static javax.swing.JLabel btninsertgv;
    public static javax.swing.JComboBox cbmscn;
    private javax.swing.JComboBox cbmshv;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    public static javax.swing.JLabel labelmsgv;
    public static javax.swing.JLabel nhan1;
    public static javax.swing.JLabel nhan2;
    private javax.swing.JTextField txtcn;
    private javax.swing.JTextField txthocvi;
    private javax.swing.JTextField txtmsgv;
    public static javax.swing.JComboBox txtmsgvcu;
    private javax.swing.JTextField txtnam;
    // End of variables declaration//GEN-END:variables
}
