/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import ConectDB.ConnectionUtil;
import static GUI.LOGIN.txtusername;
import java.awt.Color;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MSI
 */
public class insertsv extends javax.swing.JFrame {

    /**
     * Creates new form insertsv
     */
    public insertsv() {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
        txtmssv.setBackground(new Color(0,0,0,0));
        txthoten.setBackground(new Color(0,0,0,0));
        txtlop.setBackground(new Color(0,0,0,0));
        txtsdt.setBackground(new Color(0,0,0,0));
        txtdiachi.setBackground(new Color(0,0,0,0));
        txtmssvcu.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtmssvcu = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtdiachi = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txtsdt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtlop = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        txthoten = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        txtmssv = new javax.swing.JTextField();
        labelmssv = new javax.swing.JLabel();
        nhan2 = new javax.swing.JLabel();
        btnback = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nhan1 = new javax.swing.JLabel();
        btninsertsv1 = new javax.swing.JLabel();
        btneditsv = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        bg1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtmssvcu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtmssvcu.setForeground(new java.awt.Color(255, 255, 255));
        txtmssvcu.setText("Enter tên đăng nhập");
        txtmssvcu.setBorder(null);
        txtmssvcu.setCaretColor(new java.awt.Color(255, 255, 255));
        txtmssvcu.setOpaque(false);
        txtmssvcu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtmssvcuFocusGained(evt);
            }
        });
        txtmssvcu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtmssvcuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtmssvcuMouseExited(evt);
            }
        });
        txtmssvcu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmssvcuActionPerformed(evt);
            }
        });
        getContentPane().add(txtmssvcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 320, 40));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator8.setToolTipText("");
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 10, 500));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 330, 20));

        jLabel8.setFont(new java.awt.Font("UTM Avo", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 160, 40));

        txtdiachi.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtdiachi.setForeground(new java.awt.Color(255, 255, 255));
        txtdiachi.setText("Enter Email");
        txtdiachi.setBorder(null);
        txtdiachi.setCaretColor(new java.awt.Color(255, 255, 255));
        txtdiachi.setOpaque(false);
        txtdiachi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtdiachiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtdiachiMouseExited(evt);
            }
        });
        txtdiachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiachiActionPerformed(evt);
            }
        });
        getContentPane().add(txtdiachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 320, 40));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 610, 332, 10));

        txtsdt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtsdt.setForeground(new java.awt.Color(255, 255, 255));
        txtsdt.setText("Enter SODT");
        txtsdt.setBorder(null);
        txtsdt.setCaretColor(new java.awt.Color(255, 255, 255));
        txtsdt.setOpaque(false);
        txtsdt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtsdtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtsdtMouseExited(evt);
            }
        });
        txtsdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsdtActionPerformed(evt);
            }
        });
        getContentPane().add(txtsdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 320, 40));

        jLabel7.setFont(new java.awt.Font("UTM Avo", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Số điện thoại:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 160, 40));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 332, 10));

        jLabel6.setFont(new java.awt.Font("UTM Avo", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Chức danh:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 160, 40));

        txtlop.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtlop.setForeground(new java.awt.Color(255, 255, 255));
        txtlop.setText("Enter Chức danh");
        txtlop.setBorder(null);
        txtlop.setCaretColor(new java.awt.Color(255, 255, 255));
        txtlop.setOpaque(false);
        txtlop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtlopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtlopMouseExited(evt);
            }
        });
        txtlop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlopActionPerformed(evt);
            }
        });
        getContentPane().add(txtlop, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 320, 40));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(0, 4));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 332, 10));

        jLabel5.setFont(new java.awt.Font("UTM Avo", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Họ và tên:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 160, 40));

        txthoten.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txthoten.setForeground(new java.awt.Color(255, 255, 255));
        txthoten.setText("Enter HOTEN");
        txthoten.setBorder(null);
        txthoten.setCaretColor(new java.awt.Color(255, 255, 255));
        txthoten.setOpaque(false);
        txthoten.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txthotenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txthotenMouseExited(evt);
            }
        });
        getContentPane().add(txthoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 320, 40));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 332, 10));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 332, 10));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");
        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 10, 500));

        txtmssv.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtmssv.setForeground(new java.awt.Color(255, 255, 255));
        txtmssv.setText("Enter tên đăng nhập");
        txtmssv.setBorder(null);
        txtmssv.setCaretColor(new java.awt.Color(255, 255, 255));
        txtmssv.setOpaque(false);
        txtmssv.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtmssvFocusGained(evt);
            }
        });
        txtmssv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtmssvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtmssvMouseExited(evt);
            }
        });
        txtmssv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmssvActionPerformed(evt);
            }
        });
        getContentPane().add(txtmssv, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 320, 40));

        labelmssv.setFont(new java.awt.Font("UTM Avo", 1, 18)); // NOI18N
        labelmssv.setForeground(new java.awt.Color(255, 255, 255));
        labelmssv.setText("Tên đăng nhập:");
        getContentPane().add(labelmssv, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 160, 40));

        nhan2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nhan2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit_property_100px.png"))); // NOI18N
        nhan2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nhan2MouseClicked(evt);
            }
        });
        getContentPane().add(nhan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/undo_60px.png"))); // NOI18N
        btnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbackMouseClicked(evt);
            }
        });
        getContentPane().add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 640, -1, -1));

        jLabel2.setFont(new java.awt.Font("UTM Avo", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Thông tin người dùng ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, 40));

        nhan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_row_100px.png"))); // NOI18N
        getContentPane().add(nhan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        btninsertsv1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_60px.png"))); // NOI18N
        btninsertsv1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btninsertsv1MouseClicked(evt);
            }
        });
        getContentPane().add(btninsertsv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 640, -1, -1));

        btneditsv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btneditsv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit_property_100px.png"))); // NOI18N
        btneditsv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneditsvMouseClicked(evt);
            }
        });
        getContentPane().add(btneditsv, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 640, -1, -1));

        bg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/insertsv.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 711));

        bg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/insertsv.png"))); // NOI18N
        getContentPane().add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 21, -1, 711));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnbackMouseClicked

    private void nhan2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhan2MouseClicked
        try {
            String mssv = txtmssv.getText();
            String tensv = txthoten.getText();
            String lop = txtlop.getText();
            String sodt = txtsdt.getText();
            String diachi = txtdiachi.getText();
            Connection conn;
            conn = ConnectionUtil.getMyConnection();
            String sql = "{call insert_table_sinhvien(?,?,?,?,?,?)}";
            CallableStatement cstm = conn.prepareCall(sql);
            cstm.setString(1, mssv);
            cstm.setString(2, tensv);
            cstm.setString(3, lop);
            cstm.setString(4, sodt);
            cstm.setString(5, diachi);
            cstm.registerOutParameter(6, java.sql.Types.INTEGER);
            cstm.executeUpdate();
            int kq= cstm.getInt(6);//gọi kết quả trả về
            if(kq==1){
                JOptionPane.showMessageDialog(null,"Insert Complete!!!!");
            }else{
                JOptionPane.showMessageDialog(null,"Fail! Please check and insert againt!!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(insertsv.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(insertsv.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nhan2MouseClicked

    private void txtlopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlopActionPerformed

    private void txtsdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsdtActionPerformed

    private void txtmssvFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmssvFocusGained
        
    }//GEN-LAST:event_txtmssvFocusGained

    private void txthotenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txthotenMouseEntered
        
    }//GEN-LAST:event_txthotenMouseEntered

    private void txtlopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtlopMouseEntered
        
    }//GEN-LAST:event_txtlopMouseEntered

    private void txtsdtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsdtMouseEntered
        
    }//GEN-LAST:event_txtsdtMouseEntered

    private void txtmssvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmssvMouseExited
        
    }//GEN-LAST:event_txtmssvMouseExited

    private void txthotenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txthotenMouseExited
        
    }//GEN-LAST:event_txthotenMouseExited

    private void txtlopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtlopMouseExited
        
    }//GEN-LAST:event_txtlopMouseExited

    private void txtsdtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsdtMouseExited
        
    }//GEN-LAST:event_txtsdtMouseExited

    private void txtmssvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmssvMouseEntered
        txtmssv.setText("");
        txthoten.setText("");
        txtdiachi.setText("");
        txtsdt.setText("");
        txtlop.setText("");
    }//GEN-LAST:event_txtmssvMouseEntered

    private void btninsertsv1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btninsertsv1MouseClicked
        try {
            String mssv = txtmssv.getText();
            String tensv = txthoten.getText();
            String lop = txtlop.getText();
            String sodt = txtsdt.getText();
            String diachi = txtdiachi.getText();
            Connection conn;
            conn = ConnectionUtil.getMyConnection();
            String sql = "{call insert_table_sinhvien(?,?,?,?,?,?)}";
            CallableStatement cstm = conn.prepareCall(sql);
            cstm.setString(1, mssv);
            cstm.setString(2, tensv);
            cstm.setString(3, lop);
            cstm.setString(4, sodt);
            cstm.setString(5, diachi);
            cstm.registerOutParameter(6, java.sql.Types.INTEGER);
            cstm.executeUpdate();
            int kq= cstm.getInt(6);//gọi kết quả trả về
            if(kq==1){
                JOptionPane.showMessageDialog(null,"Insert Complete!!!!");
            }else{
                JOptionPane.showMessageDialog(null,"Fail! Please check and insert againt!!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(insertsv.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(insertsv.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btninsertsv1MouseClicked

    private void btneditsvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditsvMouseClicked
        try {
            String mssvcu = txtmssvcu.getText();
            String mssvmoi = txtmssv.getText();
            String tensv = txthoten.getText();
            String lop = txtlop.getText();
            String sodt = txtsdt.getText();
            Connection conn;
            conn = ConnectionUtil.getMyConnection();
            String sql = "{call capnhat_sinhvien(?,?,?,?,?,?)}";
            CallableStatement cstm = conn.prepareCall(sql);
            cstm.setString(1, mssvcu);
            cstm.setString(2, mssvmoi);
            cstm.setString(3, tensv);
            cstm.setString(4, lop);
            cstm.setString(5, sodt);
            cstm.registerOutParameter(6, java.sql.Types.INTEGER);
            cstm.executeUpdate();
            int kq= cstm.getInt(6);//gọi kết quả trả về
            if(kq==1){
                JOptionPane.showMessageDialog(null,"Update Complete!!!!");
            }else{
                JOptionPane.showMessageDialog(null,"Fail! Please check and update againt!!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(insertsv.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(insertsv.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btneditsvMouseClicked

    private void txtmssvcuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmssvcuFocusGained
          txtmssvcu.setText("");
    }//GEN-LAST:event_txtmssvcuFocusGained

    private void txtmssvcuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmssvcuMouseEntered
      
    }//GEN-LAST:event_txtmssvcuMouseEntered

    private void txtmssvcuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmssvcuMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmssvcuMouseExited

    private void txtmssvcuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmssvcuActionPerformed
        
    }//GEN-LAST:event_txtmssvcuActionPerformed

    private void txtdiachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiachiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiachiActionPerformed

    private void txtdiachiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdiachiMouseExited

    }//GEN-LAST:event_txtdiachiMouseExited

    private void txtdiachiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdiachiMouseEntered

    }//GEN-LAST:event_txtdiachiMouseEntered

    private void txtmssvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmssvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmssvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insertsv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insertsv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insertsv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insertsv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insertsv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bg1;
    private javax.swing.JLabel btnback;
    public static javax.swing.JLabel btneditsv;
    public static javax.swing.JLabel btninsertsv1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    public static javax.swing.JLabel labelmssv;
    public static javax.swing.JLabel nhan1;
    public static javax.swing.JLabel nhan2;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtlop;
    private javax.swing.JTextField txtmssv;
    public static javax.swing.JTextField txtmssvcu;
    private javax.swing.JTextField txtsdt;
    // End of variables declaration//GEN-END:variables
}
